name = "links"
main = "src/index.ts"
compatibility_date = "2022-11-25"

workers_dev = true
routes = [
	{ pattern = "l.jacoblin.cool", custom_domain = true, zone_name = "jacoblin.cool" },
	{ pattern = "l.csie.cool", custom_domain = true, zone_name = "csie.cool" }
]

[[kv_namespaces]]
binding = "STORAGE"
id = "044a5b30bf974d06910ec45a3f30a87e"
preview_id = "bff97430971d48b3902e470aa1d01809"

[vars]
# PASS = "LINKS_OWNER_PASSWORD" You should set this in the dashboard
# EMAIL_NOTIFY = "THE_EMAIL_TO_NOTIFY" Optional, if set, will send an email to this address when a link is accessed by someone
# DISCORD_NOTIFY = "DISCORD_WEBHOOK_URL" Optional, if set, will send a message to this webhook when a link is accessed by someone
